### ISSUE TITLE
[Setting] 프로젝트 초기 설정 

### ISSUE THREAD

**Issue by 0lynny** [0lynny/SF_Server#1]
## 🛠 Issue

프로젝트 초기 설정

## 🚀 To-do

- [x] 프로젝트 init
- [x] AWS EC2, RDS 설정
- [x] 폴더링 구조
- [x] gitignore 설정 변경
- [x] application.yml 프로필 및 secret 분리
